// Sample quotes array
const quotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "We cannot solve problems with the kind of thinking we employed when we came up with them. — Albert Einstein",
    "Stay away from those people who try to disparage your ambitions. Small minds will always do that, but great minds will give you a feeling that you can become great too. — Mark Twain",
    "When you give joy to other people, you get more joy in return. You should give a good thought to happiness that you can give out.— Eleanor Roosevelt",
    "It is only when we take chances, when our lives improve. The initial and the most difficult risk that we need to take is to become honest. —Walter Anderson",
    "Nature has given us all the pieces required to achieve exceptional wellness and health, but has left it to us to put these pieces together.—Diane McLaren",
    "Success is not final; failure is not fatal: It is the courage to continue that counts. — Winston S. Churchill",
    "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success. —Dale Carnegie",
    "There are three ways to ultimate success: The first way is to be kind. The second way is to be kind. The third way is to be kind. —Mister Rogers",
    "Success is peace of mind, which is a direct result of self-satisfaction in knowing you made the effort to become the best of which you are capable. —John Wooden",
    "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. — Winston Churchill",
    "In order to be irreplaceable one must always be different. —Coco Chanel",
    "Anything can make me stop and look and wonder, and sometimes learn. —Kurt Vonnegut",
    "People's passion and desire for authenticity is strong. —Constance Wu",
    "A surplus of effort could overcome a deficit of confidence. —Sonia Sotomayor",
    "Doubt is a killer. You just have to know who you are and what you stand for. —Jennifer Lopez",
    "No one changes the world who isn't obsessed. —Billie Jean King",
    "When I believe in something, I'm like a dog with a bone. —Melissa McCarthy",
    "The standard you walk past, is the standard you accept. —David Hurley",
    "Success is stumbling from failure to failure with no loss of enthusiasm. ―Winston Churchill",
    "Keep your eyes on the stars, and your feet on the ground. ―Theodore Roosevel",
    "Perfection is not attainable. But if we chase perfection we can catch excellence. —Vince Lombardi",
    "Get a good idea and stay with it. Dog it, and work at it until it's done right. —Walt Disney",
    "Learn as if you will live forever, live like you will die tomorrow. — Mahatma Gandhi",
    "When you change your thoughts, remember to also change your world.—Norman Vincent Peale",
    "It is better to fail in originality than to succeed in imitation.— Herman Melville",
    "The road to success and the road to failure are almost exactly the same. — Colin R. Davis",
    "Success usually comes to those who are too busy looking for it. — Henry David Thoreau",
    "I never dreamed about success. I worked for it. —Estée Lauder",
    "Success is getting what you want, happiness is wanting what you get. ―W. P. Kinsella",
    "Don't let yesterday take up too much of today. — Will Rogers",
    "To know how much there is to know is the beginning of learning to live. —Dorothy West",
    "Goal setting is the secret to a compelling future. — Tony Robbins",
    "Either you run the day or the day runs you. — Jim Rohn",
    "Setting goals is the first step in turning the invisible into the visible. — Tony Robbins",
    "Women challenge the status quo because we are never it. — Cindy Gallop",
    "The thing women have yet to learn is nobody gives you power. You just take it.  ― Roseanne Barr",
    "Somewhere, something incredible is waiting to be known. —Carl Sagan",
    "If you don't risk anything, you risk even more. —Erica Jong",
    "Failure is simply the opportunity to begin again, this time more intelligently. — Henry Ford",
    "Our greatest glory is not in never falling, but in rising every time we fall. — Confucius",
    "If you change the way you look at things, the things you look at change. — Wayne Dyer",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit. — Aristotle",
    "Start where you are. Use what you have. Do what you can. — Arthur Ashe",
    "Hustle beats talent when talent doesn't hustle - Ross Simmonds",
    "Make sure your worst enemy doesn' live between your own two ears. —Laird Hamilton",
    "It is a rough road that leads to the heights of greatness. —Lucius Annaeus Seneca",
    "If we take care of the moments, the years will take care of themselves. —Maria Edgeworth",
    "Resilience is when you address uncertainty with flexibility. —Unknown",
    "True humility is not thinking less of yourself; it is thinking of yourself less. — C.S. Lewis",
    "Nothing ever goes away until it teaches us what we need to know.- Pema Chodron",
    "The best way out is always through. ―Robert Frost",
    "If there is no struggle, there is no progress. —Frederick Douglass",
    "Courage is like a muscle. We strengthen it by use. —Ruth Gordo",
    "More is lost by indecision than wrong decision. —Marcus Tullius Cicero",
    "Keep a little fire burning; however small, however hidden. ―Cormac McCarthy",
    "I think it's intoxicating when somebody is so unapologetically who they are. —Don Cheadle",
    "You can never leave footprints that last if you are always walking on tiptoe. —Leymah Gbowee",
    "If you don't like the road you're walking, start paving another one. —Dolly Parton",
    "If it makes you nervous, you're doing it right. —Childish Gambino",
    "I choose to make the rest of my life the best of my life. —Louise Hay",
    "The most difficult thing is the decision to act, the rest is merely tenacity. —Amelia Earhart",
    "Work until your bank account looks like a phone number. — Unknown",
    "I am so clever that sometimes I don't understand a single word of what I am saying. — Oscar Wilde",
    "People say nothing is impossible, but I do nothing every day. — Winnie the Pooh",
    "Life is like a sewer… what you get out of it depends on what you put into it. — Tom Lehrer",
    "Talent wins games, but teamwork and intelligence win championships. — Michael Jordan",
    "Alone we can do so little, together we can do so much. — Helen Keller",
    "Just one small positive thought in the morning can change your whole day. — Dalai Lama",
    "Opportunities don't happen, you create them. — Chris Grosser",
    "You learn more from failure than from success. Don't let it stop you. Failure builds character. — Unknown",
    "If you are working on something that you really care about, you don't have to be pushed. The vision pulls you. — Steve Jobs",
    "Experience is a hard teacher because she gives the test first, the lesson afterwards.―Vernon Sanders Law",
    "Concentrate all your thoughts upon the work in hand. The sun's rays do not burn until brought to a focus.  — Alexander Graham Bell",
    "I'm a greater believer in luck, and I find the harder I work the more I have of it.— Thomas Jefferson",
    "When we strive to become better than we are, everything around us becomes better too. — Paulo Coelho",
    "Opportunity is missed by most people because it is dressed in overalls and looks like work. — Thomas Edison",
    "Don't settle. As with all matters of the heart, you'll know when you find it. — Steve Job",
    "It's not about better time management. It's about better life management— Alexandra of The Productivity Zone",
    "We don't just sit around and wait for other people. We just make, and we do. — Arlan Hamilton",
    "Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness. — Oprah Winfrey",
    "The strongest actions for a woman is to love herself, be herself and shine amongst those who never believed she could. — Unknown",
    "Whenever you see a successful woman, look out for three men who are going out of their way to try to block her. - Yulia Tymoshenko",
    "Some women choose to follow men, and some choose to follow their dreams. If you're wondering which way to go, remember that your career will never wake up and tell you that it doesn;t love you anymore.— Lady Gaga",
    "If you want something said, ask a man; if you want something done, ask a woman. -Margaret Thatcher",
    "We need women at all levels, including the top, to change the dynamic, reshape the conversation, to make sure women's voices are heard and heeded, not overlooked and ignored.- Sheryl Sandberg",
    "I swear, by my life and my love of it, that I will never live for the sake of another man, nor ask another man to live for mine — Ayn Rand",
    "Love your family, work super hard, live your passion. — Gary Vaynerchuk",
    "It is never too late to be what you might have been.— George Eliot",
    "Don't let someone else's opinion of you become your reality — Les Brown",
    "If you're not positive energy, you're negative energy. Mark Cuban",
    "I am not a product of my circumstances. I am a product of my decisions. — Stephen R. Covey",
    "I'd rather regret the things I've done than regret the things I haven't done. —Lucille Ball",
    "You cannot plow a field by turning it over in your mind. To begin, begin. ―Gordon B. Hinckley",
    "Mondays are the start of the work week which offer new beginnings 52 times a year! - David Dweck",
    "Friday sees more smiles than any other day of the workweek!—Kate Summers",
    "Inspiration does exist, but it must find you working. —Pablo Picasso",
    "Show up, show up, show up, and after a while the muse shows up, too. —Isabel Allende",
    "Don't bunt. Aim out of the ballpark. Aim for the company of immortals. ―David Ogilvy",
    "I have stood on a mountain of no's for one yes. —Barbara Elaine Smith",
    "Don't look at your feet to see if you are doing it right. Just dance. ―Anne Lamott",
    "True freedom is impossible without a mind made free by discipline. ―Mortimer J. Adler",
    "One secret of success in life is for a man to be ready for his opportunity when it comes. - Benjamin Disraeli",
    "A man who has committed a mistake and doesn't correct it is committing another mistake. - Confucius Kongzi",
    "The successful man will profit from his mistakes and try again in a different way. - Dale Carnegie",
    "A successful man is one who can lay a firm foundation with the bricks others have thrown at him. - David Brinkley",
    "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has. - Epictetus",
    "You've got to get up every morning with determination if you're going to go to bed with satisfaction. — George Lorimer",
    "You'll find that education is just about the only thing lying around loose in this world, and it's about the only thing a fellow can have as much of as he's willing to haul away. —John Graham",
    "Take the attitude of a student, never be too big to ask questions, never know too much to learn something new. —Augustine Og Mandino",
    "The elevator to success is out of order. You'll have to use the stairs, one step at a time. — Joe Girard",
    "Be a positive energy trampoline - absorb what you need and rebound more back. — Dave Carolan",
    "People often say that motivation doesn't last. Well, neither does bathing - that's why we recommend it daily. — Zig Ziglar",
    "Coming together is a beginning. Keeping together is progress. Working together is success. — Henry Ford",
    "Remember, teamwork begins by building trust. And the only way to do that is to overcome our need for invulnerability. — Patrick Lencioni",
    "I invite everyone to choose forgiveness rather than division, teamwork over personal ambition. — Jean-Francois Cope",
    "The greatest discovery of my generation is that a human being can alter his life by altering his attitudes. — William James",
    "One of the differences between some successful and unsuccessful people is that one group is full of doers, while the other is full of wishers. — Edmond Mbiaka",
    "Challenges are the stepping stones to greatness; embrace them with courage.",
    "Love is the compass that guides us through the journey of the heart.",
    "Your attitude determines your direction; choose positivity.",
    "In the symphony of life, find your unique melody and play it with passion.",
    "The only way to do great work is to love what you do - Steve Jobs.",
    "Kindness is the golden chain by which society is bound together.",
    "Dream big, work hard, stay focused, and surround yourself with good people.",
    "Life is short; make every moment count.",
    "Success is not the key to happiness; happiness is the key to success.",
    "The smallest act of kindness is worth more than the grandest intention",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Every sunset is an opportunity to reset.",
    "In the dance of change, discover the rhythm of growth.",
    "Your potential is endless; go explore it.",
    "Hope is the anchor for the soul in the stormy sea of life.",
    "Be a voice, not an echo; stand out and make a difference.",
    "Every cloud has a silver lining; find the beauty in adversity.",
    "The secret of getting ahead is getting started - Mark Twain.",
    "Gratitude turns what we have into enough.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "Wisdom is the reward you get for a lifetime of listening when you'd have preferred to talk.",
    "Courage is not the absence of fear, but the triumph over it.",
    "Change the world by being yourself.",
    "It's not about the destination, but the journey that shapes us.",
    "Believe you can, and you're halfway there.",
    "The best way to predict the future is to create it.",
    "Happiness is not by chance, but by choice.",
    "Your life does not get better by chance; it gets better by change.",
    "Success is stumbling from failure to failure with no loss of enthusiasm.",
    "Kindness is a language that the deaf can hear and the blind can see.",
    "Be the change you want to see in the world.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Dwell on the beauty of life; watch the stars, and see yourself running with them.",
    "A dream you dream alone is only a dream. A dream you dream together is reality.",
    "The best preparation for tomorrow is doing your best today.",
    "The only person you are destined to become is the person you decide to be.",
    "You are never too old to set another goal or to dream a new dream.",
    "Life is what happens when you're busy making other plans - John Lennon.",

    
    ];

function getRandomQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    const quoteElement = document.getElementById('quote');
    quoteElement.textContent = quotes[randomIndex];
}

// Initial quote on page load
getRandomQuote();
